# Fake News Classifier Using LSTM

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv',)

In [5]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [6]:
df.shape

(20800, 5)

In [7]:
df = df.dropna()

In [8]:
df.shape

(18285, 5)

In [9]:
X = df.drop('label',axis=1)
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [10]:
 y = df['label']

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

In [12]:
#Vocabulary size
voc_size = 5000

# Onehot Representation

In [13]:
message = X.copy()
message

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [14]:
message['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [15]:
message.reset_index(inplace=True)

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KRUSHNA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# Data Preprocessing

In [27]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(message)):
    review = re.sub('[^a-zA-Z]',' ',message['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    

In [20]:
len(message)

18285

In [28]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [29]:
onehot_repr = [one_hot(words,voc_size)for words in corpus]
onehot_repr

[[111, 1091, 4668, 2812, 1655, 1757, 883, 3747, 4746, 4977],
 [1823, 1185, 4363, 1794, 1961, 161, 3171],
 [3063, 1105, 3396, 4055],
 [327, 3071, 4702, 2432, 4436, 1910],
 [4602, 1961, 4330, 821, 3489, 973, 1961, 2234, 4204, 4530],
 [4248,
  2799,
  747,
  3878,
  1413,
  3482,
  3425,
  1360,
  392,
  2383,
  1919,
  2044,
  238,
  1705,
  3171],
 [4420, 4209, 3749, 2278, 956, 4403, 73, 796, 3880, 2560, 2695],
 [3685, 1517, 2251, 452, 814, 1938, 3482, 2192, 3880, 2560, 2695],
 [1998, 2429, 3971, 4272, 4513, 2404, 1201, 4547, 3482, 4069],
 [1647, 2867, 4591, 3583, 3802, 1993, 2354, 3891],
 [3143, 4449, 1314, 4183, 3777, 3198, 3265, 1188, 392, 3373, 4841],
 [2432, 2517, 1655, 2404, 3482, 814],
 [748, 2162, 1524, 2540, 4320, 1942, 4825, 613, 3154],
 [4983, 25, 1610, 119, 1358, 4380, 4310, 3880, 2560, 2695],
 [3782, 2344, 1179, 4148, 3939, 3880, 2560, 2695],
 [2669, 3583, 1710, 4618, 3762, 302, 2281, 2453, 395, 571],
 [459, 4002, 1185],
 [3601, 4927, 4325, 2754, 3482, 608, 4291, 3171],
 [3

# Embedding Representation

In [30]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 3747 4746 4977]
 [   0    0    0 ... 1961  161 3171]
 [   0    0    0 ... 1105 3396 4055]
 ...
 [   0    0    0 ... 3880 2560 2695]
 [   0    0    0 ...  100  949 1038]
 [   0    0    0 ... 1582 4027 4557]]


In [31]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  111,
       1091, 4668, 2812, 1655, 1757,  883, 3747, 4746, 4977])

In [32]:
#Creating model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [36]:
len(embedded_docs),y.shape

(18285, (18285,))

In [38]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [39]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [84]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.33,random_state=42)

# Model Training

In [85]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 15s 52ms/step - loss: 0.3514 - accuracy: 0.8363 - val_loss: 0.2091 - val_accuracy: 0.9090
Epoch 2/10
192/192 [==============================] - 9s 45ms/step - loss: 0.1509 - accuracy: 0.9407 - val_loss: 0.1923 - val_accuracy: 0.9190
Epoch 3/10
192/192 [==============================] - 8s 44ms/step - loss: 0.1083 - accuracy: 0.9605 - val_loss: 0.2074 - val_accuracy: 0.9196
Epoch 4/10
192/192 [==============================] - 8s 44ms/step - loss: 0.0801 - accuracy: 0.9721 - val_loss: 0.2234 - val_accuracy: 0.9145
Epoch 5/10
192/192 [==============================] - 8s 44ms/step - loss: 0.0564 - accuracy: 0.9805 - val_loss: 0.2757 - val_accuracy: 0.9171
Epoch 6/10
192/192 [==============================] - 8s 44ms/step - loss: 0.0420 - accuracy: 0.9851 - val_loss: 0.3472 - val_accuracy: 0.9183
Epoch 7/10
192/192 [==============================] - 9s 46ms/step - loss: 0.0291 - accuracy: 0.9900 - val_loss: 0.3339 - val_accuracy: 0.915

# Adding Dropout

In [86]:
from tensorflow.keras.layers import Dropout
##Creating model
embedding_vector_features=40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

# Performance Metrics And Accuracy

In [87]:
y_pred = model.predict(X_test).astype("int32")

189/189 [==============================] - 3s 10ms/step


In [93]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [89]:
from sklearn.metrics import confusion_matrix


In [90]:
confusion_matrix(y_test,y_pred)

array([[3419,    0],
       [2616,    0]], dtype=int64)

In [91]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5665285832642917

6035